# Layered Modbus RTU — portable core + host selftest
# STM32 sources are built inside CubeIDE / Makefile generated by CubeMX.

CC      ?= gcc
CFLAGS  ?= -std=c99 -Wall -Wextra -O2 \
           -Iconfig -Icore/include -Iport/include
LDFLAGS ?=

CORE_SRC = \
	core/src/modbus_types.c \
	core/src/modbus_crc.c \
	core/src/modbus_rtu.c \
	core/src/modbus_map.c \
	core/src/modbus_master.c \
	core/src/modbus_slave.c

CORE_OBJ = $(CORE_SRC:.c=.o)
LIB = libmodbus_rtu_core.a

.PHONY: all clean test

all: $(LIB) selftest

$(LIB): $(CORE_OBJ)
	ar rcs $@ $^

core/src/%.o: core/src/%.c
	$(CC) $(CFLAGS) -c $< -o $@

selftest: examples/selftest.c $(LIB)
	$(CC) $(CFLAGS) $< -L. -lmodbus_rtu_core $(LDFLAGS) -o $@

test: selftest
	./selftest

clean:
	rm -f $(CORE_OBJ) $(LIB) selftest selftest.exe
